### ISSUE TITLE
Oddaja projektne naloge

### ISSUE THREAD

**Issue by EvaRudolf** [EvaRudolf/APPR-2021-22#1]
Pozdravljeni!
Projekt oddajam v ocenjevanje.
Lep pozdrav,
Eva Rudolf

**Comment by M4rble** [comment]
Zdravo,
poročilo projekta se prevede brez težav, z oddajo projekta je vse v redu.
Projekt bo ocenjen v naslednjih dneh.
Lp, Anže

**Comment by katarinabrilej** [comment]
Meni se zdi, da sta zemljevid1 in zemljevid2 v poročilu zamenjana (morda se motim).

**Comment by EvaRudolf** [comment]
Imate prav, sem popravila.

**Comment by katarinabrilej** [comment]
Ocena in komentar sta vpisana v spletni učilnici.

**Comment by EvaRudolf** [comment]
Sem videla, hvala!
